### ISSUE TITLE
API not working with Postgres, Using manual install! (Solved)

### ISSUE THREAD

**Issue by 17mafo** [csgofloat/inspect#102]
So the problem I had was that when trying to use the API to fetch item data it would get stuck on loading the page. and nothing would appear in the console, Also the /stats page was working. I am using Postgres v12.9

**The solution** I found for me was to upgrade the pg version from "v7.18.2" (which is automatically installed) to the newest "v8.7.3" after that the API worked like a charm! 😄 

I know it's recommended to use the docker image but since docker does not install the Postgres database this problem should still occur? (I don't really know how to use docker so please correct me if I'm wrong!)

Also Thank you for making csgofloat free and open source! 😄

**Comment by AboutSange** [comment]
@17mafo Thank you !!!
The problem also occurred in my centos, Now it's solved in your way.

> Environment
- centos 7.9
- Postgres 9.2.24 (auto installed using yum)
- npm 6.14.12
- node 10.24.1
- Node dependency package pg 7.18.2

> Problem Description

1.  I deployed this project using docker and run it after adjust the conf;
2.  Visit http://x.x.x.x/stats, It's working normal: 
`{"bots_online":1,"bots_total":1,"queue_size":0,"queue_concurrency":1}`

3. Visit http://x.x.x.x/?m=563330426657599553&a=6710760926&d=9406593057029549017, It's stuck. An error was found while checking the docker logs: 

```
(node:7) UnhandledPromiseRejectionWarning: error: relation "items" does not exist
    at Parser.parseErrorMessage (/usr/src/csgofloat/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/csgofloat/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/csgofloat/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.stream.on (/usr/src/csgofloat/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

> The solution

1.  Postgres Server: 9.2.24  -> 12.10
2.  Node dependency package pg: 7.18.2 -> 8.7.3

Now, It's working well, Thank you again!!!

**Comment by fipso** [comment]
Why is this information not in the README ? This pg version does not support anything above nodejs 14.

from their docs: ```Version compatibility
node-postgres strives to be compatible with all recent lts versions of node & the most recent "stable" version. At the time of this writing node-postgres is compatible with node 8.x, 10.x, 12.x and 14.x To use node >= 14.x you will need to install pg@8.2.x or later due to some internal stream changes on the node 14 branch. Dropping support for an old node lts version will always be considered a breaking change in node-postgres and will be done on major version number changes only, and we will try to keep support for 8.x for as long as reasonably possible.```

**Comment by Step7750** [comment]
@fipso Feel free to create a PR that bumps the version of node-pg (which is the root cause of the issue).
