### ISSUE TITLE
Error when account relogin

### ISSUE THREAD

**Issue by Luftenmensch** [csgofloat/inspect#117]
![image](https://user-images.githubusercontent.com/40238501/225216745-de37dcd7-e990-4456-aeb4-fcc508dafd21.png)
Updated inspect image ~2 days ago, after this observing this error after 30 minutes +- random time after restart the container

**Comment by mdf45** [comment]
Hello. I have the same problem. I set rememberPassword to true, but it's not working.

**Comment by mdf45** [comment]
I'm solved this. **You should to update your npm packages.**
change 'steam-totp' to 2.1.2 or [newest](https://www.npmjs.com/package/steam-totp),
change 'steam-user' to 4.28.0 or [newest](https://www.npmjs.com/package/steam-user)
and start command `npm install`
![image](https://user-images.githubusercontent.com/53022885/226975359-cea38920-0d28-43cf-84f6-126585988f93.png)

**Comment by Step7750** [comment]
v4.0.1 contains the fix, you can pull on Docker the specific version or master.
