### ISSUE TITLE
Postgres Connection

### ISSUE THREAD

**Issue by sissl0** [csgofloat/inspect#118]
Im on a Windows System.
When im using Postgres in Docker im getting: error: connect econnrefused 127.0.0.1:5432.
i found that when within Docker you should use [dbname]:5432, but this cant be resolved so the address cant be found.
So i installed Postgres directly on Windows but im getting the same error when 'database_url' = postgres://postgres:password@127.0.0.1:5432/postgres?sslmode=disable in the config file.
The Port is up in netstat and with dbeaver i can connect, so i assume i got eighter the url wrong or there is some issue with wsl.
Some said that the error is thrown by the database but im not 100% sure about that.

**Comment by Step7750** [comment]
Please learn how Docker works before making a ticket.

You likely can't access the postgres server within the container -- you can either use a custom network "bridge" or host networking.
