### ISSUE TITLE
Issue fetching with multiple requests

### ISSUE THREAD

**Issue by 222Pi** [csgofloat/inspect#123]
So I think steam has changed somewhat since this was last discussed, and now you need apart from a unique account also a unique IP per request. 

I can do single requests just fine, but once i start doing 5,10,30 (Added some 100 accounts) I immediately get the ```{
  'assetid': {
    error: "Valve's servers didn't reply in time",
    code: 4,
    status: 500
  }
}``` 

So, am I actually doing something wrong or should I add proxies to this? How do you guys actually do this?

For fetching individual steam inventories I am already forced to use proxies, but I think this is intended? Is there some sort of steam whitelist you can apply for?

**Comment by 222Pi** [comment]
related? https://github.com/csgofloat/inspect/issues/57

**Comment by Step7750** [comment]
This appears to be an issue on your side -- the GC method we use has been a bit slower in the last few days which has made timeouts more likely.

You can change how long you're willing to wait for the GC in the config.
