### ISSUE TITLE
response error

### ISSUE THREAD

**Issue by NevaYue** [csgofloat/inspect#124]
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:16)
(node:10541) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

**Comment by NevaYue** [comment]
I solve this problem. but when i press IP:port/?url=........... it dosent response

**Comment by Step7750** [comment]
Don't create duplicate issues.
