### ISSUE TITLE
Cannot response

### ISSUE THREAD

**Issue by NevaYue** [csgofloat/inspect#125]
When I press http://43.156.98.72/ it response
{"error":"Invalid Inspect Link Structure","code":2,"status":400}
When I press http://43.156.98.72/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561199182861203A29413808101D9999308948801583501
it doesn't response and xshell Not any message.How can i solve it.

**Comment by Step7750** [comment]
Make sure you configure Postgres as it states in the instructions. You likely have a broken connection to it.
