### ISSUE TITLE
TTL Exceeded (New Valve Restrictions)

### ISSUE THREAD

**Issue by SoloMReal** [csgofloat/inspect#131]
warn: Job Failed! S: 76561199401338644 A: 29598639405 D: 14592448071216162737 M: 0 IP:  Err: ttl exceeded

**Comment by aavvaavvaa** [comment]
same problem, also after that ttl exceeded my ip is on some kind of restrictions on steam, i can't even inspect an item inside the game, ingame inspection works only if i use vpn

**Comment by borisenko09** [comment]
The same problem also appeared, it is possible to use a proxy for each account when logging in will help to obtain information.

**Comment by borisenko09** [comment]
> > The same problem also appeared, it is possible to use a proxy for each account when logging in will help to obtain information.
> 
> Also I used ipv6 proxies via CMClient before and everything was okay until today. Did you tested it already ? What proxies are you using ipv4 or ipv6 ?

I just started with ipv4 a couple of hours ago the update came out, everything worked in the config file 'proxies': [], add the proxy there in the form "http://log:pass@ip:port"

**Comment by aavvaavvaa** [comment]
> > > The same problem also appeared, it is possible to use a proxy for each account when logging in will help to obtain information.
> > 
> > 
> > Also I used ipv6 proxies via CMClient before and everything was okay until today. Did you tested it already ? What proxies are you using ipv4 or ipv6 ?
> 
> I just started with ipv4 a couple of hours ago the update came out, everything worked in the config file 'proxies': [], add the proxy there in the form "http://log:pass@ip:port"

But my proxies are ipv6 so it wouldn't work if i just add an ipv6 proxy to the list, i'm using CMClient but it doesn't work right now and i getting ttl exceeded, so i have no clue how to fix this.

**Comment by Tankonyako** [comment]
i got also this today, and cannot figure out, if im add proxies after some time it happen again

**Comment by SoloMReal** [comment]
What if there’s no login/username and password in the proxy, for example could I just do:
http://127.0.0.1:8000
^ just an example 
Also how many proxies do you think we need?

**Comment by Allyans3** [comment]
```
info: ***************** Log on OK
info: ***************** Initiating GC Connection
debug: Sending GC message ClientHello
debug: Sending hello, setting timer for next attempt to 2000 ms
debug: Got handled GC message ClientWelcome
debug: Unknown SO type 2 with 1 items
debug: Unknown SO type 7 with 1 items
debug: GC connection established
info: ***************** CSGO Client Ready!
debug: Got unhandled GC message 9173
warn: ***************** CSGO unready (2), trying to reconnect!
warn: ***************** Logged off, reconnecting! (3, NoConnection)
```

Bots can't work with proxy, without is fine. HTTP with log:pass

**Comment by Luksch187** [comment]
Can you already say if your Inspect API will be opened for bots again and when? Or should I rather work on self hosting?

**Comment by gaelsuv** [comment]
> Hey foks,
> 
> Yes, Valve has imposed new IP/bot rate limits. The exact limits are unknown at this time, but you likely need to use a host of proxies in the interim,
> 
> #132 provides this support in v1.4.3
> 
> If you have more valuable findings, feel free to share here.

What if I was using directly the endpoint API to pass in inspect links? Would self hosting do the trick and start making my script work again? Thanks for your help.

**Comment by SPr3D** [comment]
Hello! I am sending requests through the python to CSGOFloatAPI, but it it gives me an error:
<Response [400]>
{"error":"Bots are temporarily not allowed on CSGOFloat Inspect API due to new rate limits imposed by Valve","code":16,"status":400}
Can I solve this problem somehow?

**Comment by Allyans3** [comment]
Valve removed old endpoint for fetching inventory https://steamcommunity.com/profiles/****************/inventory/json/730/2

```
{
"success": false,
"Error": "Unsupported request"
}
```

**Comment by gaelsuv** [comment]
> Valve removed old endpoint for fetching inventory https://steamcommunity.com/profiles/****************/inventory/json/730/2
> 
> ```
> {
> "success": false,
> "Error": "Unsupported request"
> }
> ```

And? Is this the one being called under the hood by Inspect public API?

**Comment by LexaCoronos** [comment]
How can I fix it?
{"error":"Bots are temporarily not allowed on CSGOFloat Inspect API due to new rate limits imposed by Valve","code":16,"status":400}

**Comment by AboutSange** [comment]
> Hey foks,
> 
> Yes, Valve has imposed new IP/bot rate limits. The exact limits are unknown at this time, but you likely need to use a host of proxies in the interim,
> 
> #132 provides this support in v1.4.3
> 
> If you have more valuable findings, feel free to share here.

Hi, thank you for providing the proxies params in config.js, but after I set proxies in config.js, I get error like this:

```
error: Error logging in xxx: message=Proxy connection timed out, stack=Error: Proxy connection timed out
    at ClientRequest.<anonymous> (/usr/src/csgofloat/node_modules/steam-user/components/connection_protocols/tcp.js:69:29)
    at ClientRequest.emit (node:events:513:28)
    at Socket.emitRequestTimeout (node:_http_client:848:9)
    at Object.onceWrapper (node:events:627:28)
    at Socket.emit (node:events:525:35)
    at Socket._onTimeout (node:net:570:8)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
info: Logging in xxx
```

and my proxies params like 

` 'proxies': ['http://ip1:port1', 'http://ip2:port2']`

and I have tested that all my proxies can access "https://httpbin.org/ip" normally, diff proxy has diff response time when access the website, and the response time is whthin 1-5 seconds, and it's always return 200 response code, so I don't know what the problem is and how I can solve it.

**Comment by LexaCoronos** [comment]
Hi, how to send to your api the special request used proxy for it? I code in Java and don't use any library.
Request example:
https://api.csgofloat.com/?m=6048939083370871310&a=29653911196&d=9406593057029549017

**Comment by SoloMReal** [comment]
> > Hey foks,
> > Yes, Valve has imposed new IP/bot rate limits. The exact limits are unknown at this time, but you likely need to use a host of proxies in the interim,
> > #132 provides this support in v1.4.3
> > If you have more valuable findings, feel free to share here.
> 
> Hi, thank you for providing the proxies params in config.js, but after I set proxies in config.js, I get error like this:
> 
> ```
> error: Error logging in xxx: message=Proxy connection timed out, stack=Error: Proxy connection timed out
>     at ClientRequest.<anonymous> (/usr/src/csgofloat/node_modules/steam-user/components/connection_protocols/tcp.js:69:29)
>     at ClientRequest.emit (node:events:513:28)
>     at Socket.emitRequestTimeout (node:_http_client:848:9)
>     at Object.onceWrapper (node:events:627:28)
>     at Socket.emit (node:events:525:35)
>     at Socket._onTimeout (node:net:570:8)
>     at listOnTimeout (node:internal/timers:569:17)
>     at process.processTimers (node:internal/timers:512:7)
> info: Logging in xxx
> ```
> 
> and my proxies params like
> 
> ` 'proxies': ['http://ip1:port1', 'http://ip2:port2']`
> 
> and I have tested that all my proxies can access "https://httpbin.org/ip" normally, diff proxy has diff response time when access the website, and the response time is whthin 1-5 seconds, and it's always return 200 response code, so I don't know what the problem is and how I can solve it.
