### ISSUE TITLE
Valve's servers didn't reply in time

### ISSUE THREAD

**Issue by antal-k** [csgofloat/inspect#141]
The API always respond with this, even if I have a bunch of bots added (200) and the timeout limit increased to 5s

**Comment by zyoi** [comment]
Proxies are now essential due to the implementation of new restrictions. Have you attempted to incorporate them into your setup?

#131 #132

**Comment by antal-k** [comment]
Well, then why is it successfully setting up connections if it's a proxy issue?

**Comment by zyoi** [comment]
From my understanding of the situation, the new limits impact fetching item data, not logging in. This is causing issues with floats and other data on many websites. Even the extension isn't working right.

Just a heads up, I don't use CSGOFloat/inspect at this time. Just here to help out!

**Comment by antal-k** [comment]
Alright, thanks for the help! It is still unclear to me since it worked yesterday, and it's not working now.

**Comment by Mahjalo** [comment]
> Proxies are now essential due to the implementation of new restrictions. Have you attempted to incorporate them into your setup?
> 
> #131 #132

How a do that?

**Comment by zyoi** [comment]
> > Proxies are now essential due to the implementation of new restrictions. Have you attempted to incorporate them into your setup?
> > #131 #132
> 
> How a do that?

Update CSGOFloat to the newest version and add the proxies parameter to your config, [like in config.example.js](https://github.com/csgofloat/inspect/blob/master/config.example.js#L22).

Keep in mind, this is for those self-hosting CSGOFloat API. Since you created issue #140 about the extension, this suggestion won't apply if you're only using the extension.

**Comment by Mahjalo** [comment]
> Update CSGOFloat to the newest version and add the proxies parameter to your config, [like in config.example.js](https://github.com/csgofloat/inspect/blob/master/config.example.js#L22).
> 
> Just to let you know, this is for those self-hosting CSGOFloat API. If you're only using the extension, as mentioned in issue #140, this suggestion won't apply.

It's my first time with this problem and I don't know JavaScript, There's s solution for the extension?

**Comment by zyoi** [comment]
> > Update CSGOFloat to the newest version and add the proxies parameter to your config, [like in config.example.js](https://github.com/csgofloat/inspect/blob/master/config.example.js#L22).
> > Just to let you know, this is for those self-hosting CSGOFloat API. If you're only using the extension, as mentioned in issue #140, this suggestion won't apply.
> 
> It's my first time with this problem and I don't know JavaScript, There's s solution for the extension?

At the moment, end-users can't fix this issue. It's a backend problem with CSGOFloat related to the new CSGO limits. The only solution is to wait for an updated version containing the necessary fixes.

**Comment by Mahjalo** [comment]
> At the moment, end-users can't fix this issue. It's a backend problem with CSGOFloat related to the new CSGO limits. The only solution is to wait for an updated version containing the necessary fixes.

thank bro

**Comment by Step7750** [comment]
Closing since this is related to you spamming the GC too much.
