### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by s3hito** [csgofloat/inspect#142]
Whenever I try to start it in the Docker following error message appers. Tested on windows, mac and linux and it's all the same error
![Screenshot_18](https://user-images.githubusercontent.com/124817371/234098773-1e3d9c7f-ef7b-438e-8c55-06f43e0c277a.jpg)

**Comment by s3hito** [comment]
Well I think I managed to figure out where it fails. It's on line 233 in index.js. Not clue still why it fails...
![Screenshot_19](https://user-images.githubusercontent.com/124817371/234119530-bb3b2b31-e68e-4c95-9f13-bed5911f16a1.jpg)

**Comment by zhuang42** [comment]
Yor PostgreSQL is not up.

**Comment by s3hito** [comment]
> Yor PostgreSQL is not up.

I'm not sure but I believe it's up and running. 
Here's my database url:
![image](https://user-images.githubusercontent.com/124817371/234209141-1c51a673-d930-43c4-b86c-b2a6a12d0fc4.png)

I tried connecting to my db via console using db url and it worked successfully
![image](https://user-images.githubusercontent.com/124817371/234209517-228cc536-80e8-4e74-ad16-3190086bee42.png)

**Comment by gaelsuv** [comment]
`localhost` inside a docker container do not map to `localhost` of the hosting os. Just figure out your private ipv4 address (ipconfig if you're on Windows) and use that inside `config.js`

that said, I keep getting this error, despite the fact that I'm using a proxy:
![Screenshot_834](https://user-images.githubusercontent.com/77157989/234245910-ff1dd1a9-b09c-45ea-895c-14b80b7ad45d.jpg)

**Comment by s3hito** [comment]
> 

Thanks a lot! I managed to get it working eventually. But now I'm facing the same issue the same as you do
