### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by oljaskrut** [csgofloat/inspect#143]
I use proxies from brightdata.com, 

Snippet from my config.js
proxies: [
    "http://username:pass@zproxy.lum-superproxy.io:22225",
  ],

Get this error when using proxy 
error: Error logging in wi2njrjrm: message=HTTP CONNECT 403 Bad Port, stack=Error: HTTP CONNECT 403 Bad

I suspect issue is in incorrect proxy configuration, but there is no example for it

**Comment by AboutSange** [comment]
me too

**Comment by oljaskrut** [comment]
> 

I changed my proxies to WebShare, they seem to be working when testing locally, but once I upload Cloud Run either 502 bad gateaway or timedout errors occurs.

**Comment by Step7750** [comment]
This isn't a forum for you to figure out how proxies work, closing this issue.
