### ISSUE TITLE
Valve's servers didn't reply in time

### ISSUE THREAD

**Issue by eklatzer** [csgofloat/inspect#146]
Hey, I am trying to setup the API service based on the Docker image `step7750/csgofloat:master`. It worked for some time and now we seem to be IP blocked, therefore we configured some proxies, but now get the following error:
```
{"error":"Valve's servers didn't reply in time","code":4,"status":500}
```
Also tried to set the `request_ttl` to a higher value.
Stats:
```
{"bots_online":1,"bots_total":1,"queue_size":0,"queue_concurrency":1}
```

Is there anything that needs to be configured in addition to the ip/port of the proxy (auth for the proxy is IP based)?

Thanks in advance

**Comment by antal-k** [comment]
Add more bot & proxies

**Comment by eklatzer** [comment]
@LexaCoronos It seems like one proxy per bot is enough: https://github.com/csgofloat/inspect/blob/35ca4d72e26643e255fd38d0fc38f9b403b6d5e2/index.js#L40
