### ISSUE TITLE
service down with error 'EAI_AGAIN' and 'Logged off'

### ISSUE THREAD

**Issue by mdf45** [csgofloat/inspect#147]
Service down with error 'EAI_AGAIN'.
![image](https://user-images.githubusercontent.com/53022885/235252615-3a7471a1-8868-462f-99fd-f76d349976e4.png)
Also I use http proxies and accounts in service lose session on reconnecting (Logged off)

**Comment by Step7750** [comment]
This is an issue with DNS lookups in your environment, closing.
