### ISSUE TITLE
Proxy Blocked: Works on one vps but not another

### ISSUE THREAD

**Issue by SoloMReal** [csgofloat/inspect#150]
> > Hey foks,
> > Yes, Valve has imposed new IP/bot rate limits. The exact limits are unknown at this time, but you likely need to use a host of proxies in the interim,
> > #132 provides this support in v1.4.3
> > If you have more valuable findings, feel free to share here.
> 
> Hi, thank you for providing the proxies params in config.js, but after I set proxies in config.js, I get error like this:
> 
> ```
> error: Error logging in xxx: message=Proxy connection timed out, stack=Error: Proxy connection timed out
>     at ClientRequest.<anonymous> (/usr/src/csgofloat/node_modules/steam-user/components/connection_protocols/tcp.js:69:29)
>     at ClientRequest.emit (node:events:513:28)
>     at Socket.emitRequestTimeout (node:_http_client:848:9)
>     at Object.onceWrapper (node:events:627:28)
>     at Socket.emit (node:events:525:35)
>     at Socket._onTimeout (node:net:570:8)
>     at listOnTimeout (node:internal/timers:569:17)
>     at process.processTimers (node:internal/timers:512:7)
> info: Logging in xxx
> ```
> 
> and my proxies params like
> 
> ` 'proxies': ['http://ip1:port1', 'http://ip2:port2']`
> 
> and I have tested that all my proxies can access "https://httpbin.org/ip" normally, diff proxy has diff response time when access the website, and the response time is whthin 1-5 seconds, and it's always return 200 response code, so I don't know what the problem is and how I can solve it.

I have the same issue.

_Originally posted by @SoloMReal in https://github.com/csgofloat/inspect/issues/131#issuecomment-1529346654_

**Comment by SoloMReal** [comment]
Nevermind, doesnt work on either.

**Comment by Step7750** [comment]
This is not relevant to the CSGOFloat Inspect server -- we aren't here to debug how your proxies work.
