### ISSUE TITLE
Inventory inspect

### ISSUE THREAD

**Issue by Viiict0r** [csgofloat/inspect#152]
Hi guys,

I'm going to start using the csgofloat api to inspect my users' items, but I wanted to know the best strategy for loading user items, taking into account that Valve has an aggressive rate limit?

**Comment by Step7750** [comment]
> I'm going to start using the csgofloat api to inspect my users' items

You'll want to host the Docker image yourself, the public API is restricted to the extension only right now.

> but I wanted to know the best strategy for loading user items, taking into account that Valve has an aggressive rate limit

We have no specifics on the rate limits to share. Likewise we have no idea what QPS or scale of inventories you're trying to fetch for -- you'll likely need many bots and proxies depending on QPS.
