### ISSUE TITLE
correct proxy config 

### ISSUE THREAD

**Issue by 222Pi** [csgofloat/inspect#154]
What is the correct proxy format to use for http proxies? I've tried https://github.com/DoctorMcKay/node-stdlib#getproxyagentsecure-proxyurl-proxytimeout (i.e user:pass@ip:port) but also user:pass:ip:port and ip:port@:user:pass - (both comb)

Whatever combination, no requests seem to be made over the proxy (which is a single var inside the 'proxies'=[] config field, e.g ```'proxies':["http://user:pass@rotatingproxyprovider.com:port"],```)

Bots will log in normally, there is no error log in the docker tab (except the 500 status when it inevitably gets rate limited) (i.e warn: Job Failed! S: A: D: M: 0 IP: ::ffff:172.17.0.1, Err: ttl exceeded)

My proxy provider does not show any activity (does log all other requests I make using their proxies), and whenever I change my host ip, bots are no longer limited, so they are definitely not using a proxy.. Quick solution?

thanks for all the effort you guys are putting into this

**Comment by BrijeshSinghal** [comment]
hello, how did you resolve this?
