### ISSUE TITLE
Correct proxy config, allow user/pass?

### ISSUE THREAD

**Issue by 222Pi** [csgofloat/inspect#155]
What is the correct proxy format to use for http proxies? I've tried https://github.com/DoctorMcKay/node-stdlib#getproxyagentsecure-proxyurl-proxytimeout (i.e user:pass@ip:port) but also user:pass:ip:port and ip:port@:user:pass - (both comb)

only thing that works is ip:port and authorizing my ip but this is not feasible or supported by some providers.

e.g support for ```ip:port:user:pass``` or ```user:pass@domain/ip:port```, which is what most rotating proxy providers offer.

**Comment by Step7750** [comment]
I believe this is an issue on your side - either way, feel free to dig in and contribute to the repo.

**Comment by entrailz** [comment]
A large portion of residential proxy providers block access to Steam, this is likely what you're experiencing. @222Pi

**Comment by 222Pi** [comment]
> A large portion of residential proxy providers block access to Steam, this is likely what you're experiencing. @222Pi

I think you're right :/ I was able to query other stuff just fine with the same proxies (market prices etc) but can't log in.

**Comment by testnetprotonmail** [comment]
> A large portion of residential proxy providers block access to Steam, this is likely what you're experiencing. @222Pi

offtopic but do you have any recommendations
