### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gazzi777** [csgofloat/inspect#159]
Request: https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198084749846A698323590D7935523998312483177

Output: {"code":13,"error":"Invalid Origin","status_code":400}

How fix this error?

**Comment by Step7750** [comment]
This is intentional, the public API is meant for extension users.

**Comment by gazzi777** [comment]
Ок что мне сделать, чтобы у меня получилось это API мне нужно скачать и установить этот репозиторий?
