### ISSUE TITLE
Bots are temporarily not allowed on CSGOFloat Inspect API due to new rate limits imposed by Valve

### ISSUE THREAD

**Issue by nkowalchuk301** [csgofloat/inspect#161]
api.csgofloat = {"error":"Bots are temporarily not allowed on CSGOFloat Inspect API due to new rate limits imposed by Valve","code":16,"status":400}

"My own host" = {"error":"Valve's servers appear to be offline, please try again later","code":5,"status":503}

Do we just wait for the bot ban to be lifted? I'm maybe sending like 1 request every 5 minutes, **If that**.

**Comment by Step7750** [comment]
There is no ETA, you should host it yourself if you need it. Sorry!

**Comment by nkowalchuk301** [comment]
I am hosting it myself. It was working 3 days ago and stopped working.

“‘My own host’ = {"error":"Valve's servers appear to be offline, please try again later","code":5,"status":503}”
