### ISSUE TITLE
[Self-hosted] "Valve's servers appear to be offline, please try again later" - only on some items

### ISSUE THREAD

**Issue by exodraft** [csgofloat/inspect#169]
Hi there !

I'm hosting a csgofloat api on my vps server, configured with my own steam account.
It works fine except for some items that return this error (using either /bulk or / ) : 
![image](https://github.com/csgofloat/inspect/assets/19282215/62038ca4-e82f-4cd7-8bfc-b7b4d5d3abd6)

Which corresponds to this steam link : `steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561199181432917A30644335605D7800881385308199593`

The official FloatChecker (https://csgofloat.com/checker) is doing fine with it though.

I can't wrap my head around it, am I missing something ? Or is this a qualifcated issue ?

**Comment by LordByronRS** [comment]
I've got the exact same issue. Did you find a fix?

**Comment by Step7750** [comment]
There are some items that can't be inspected for a small amount of time, but this is pretty rare.

Unfortunately, we don't have enough info on your setup to debug this further.
