### ISSUE TITLE
Using tremendous amounts of requests/bandwidth downloads

### ISSUE THREAD

**Issue by ludvigbartholdsson** [csgofloat/inspect#170]
Hello,

I am using an `httpProxy` with around 200 bots using this package. Is it normal for it to make 26,000 requests, while only around 9,000 of them are for actual skin-inspections?

Below is a list of all the IP addresses my proxy has accessed.

| Host                   | Sum of count | Sum of download | Sum of upload |
|----------------------- |-------------:|---------------:|--------------:|
| api.steampowered.com:443| 7,090        | 31.9MB         | 9.8MB         |
| 162.254.192.87:27018   | 85           | 20.2MB         | 819.8KB       |
| 162.254.195.66:27017   | 83           | 24.4MB         | 1.1MB         |
| 162.254.196.84:27018   | 83           | 18.1MB         | 874.6KB       |
| 162.254.198.44:27018   | 83           | 19.4MB         | 875.7KB       |
| 162.254.195.66:27018   | 82           | 22MB           | 951.1KB       |
| 155.133.246.35:27018   | 81           | 20.1MB         | 907.9KB       |
| 103.28.54.171:27017    | 80           | 23.7MB         | 1MB           |
| 146.66.155.54:27017    | 80           | 19.9MB         | 1MB           |
| 155.133.246.51:27017   | 79           | 17.8MB         | 840.2KB       |
| 155.133.252.54:27017   | 79           | 16.6MB         | 808.7KB       |
| 162.254.199.163:27018  | 79           | 19.2MB         | 826.8KB       |
| 146.66.155.54:27018    | 78           | 18.6MB         | 899.4KB       |
| 162.254.196.83:27017   | 78           | 16.1MB         | 791.2KB       |
| 103.28.54.162:27017    | 77           | 22MB           | 968.3KB       |
| 103.28.54.171:27018    | 77           | 21.5MB         | 1MB           |
| 146.66.155.38:27017    | 77           | 19.5MB         | 822.7KB       |
| 185.25.182.20:27017    | 77           | 16MB           | 689.6KB       |
| 155.133.246.36:27018   | 76           | 18.4MB         | 805.5KB       |
| 185.25.182.52:27017    | 76           | 15.9MB         | 771KB         |
| 155.133.230.50:27017   | 75           | 14.2MB         | 779KB         |
| 155.133.245.36:27018   | 75           | 20.2MB         | 895.9KB       |
| 155.133.252.39:27018   | 75           | 16.3MB         | 812.9KB       |
| 162.254.199.181:27017  | 75           | 19.9MB         | 885.1KB       |
| 162.254.199.181:27018  | 75           | 18.6MB         | 972.9KB       |
| 185.25.182.52:27018    | 75           | 17.4MB         | 854.7KB       |
| 155.133.226.78:27017   | 74           | 16.3MB         | 820.1KB       |
| 155.133.239.20:27018   | 74           | 19.9MB         | 971.1KB       |
| 155.133.246.52:27017   | 74           | 17.3MB         | 817.5KB       |
| 155.133.252.39:27017   | 74           | 16.5MB         | 788.1KB       |
| 162.254.197.54:27018   | 74           | 14.8MB         | 756KB         |
| 162.254.198.104:27017  | 74           | 16.4MB         | 753.4KB       |
| 155.133.245.37:27017   | 73           | 19.2MB         | 956.3KB       |
| 162.254.192.74:27017   | 73           | 17.6MB         | 888.4KB       |
| 155.133.253.50:27017   | 72           | 21MB           | 902.3KB       |
| 205.196.6.215:27017    | 72           | 20.9MB         | 930.6KB       |
| 103.28.54.178:27018    | 71           | 19.9MB         | 932.6KB       |
| 155.133.245.36:27017   | 71           | 15.3MB         | 767.6KB       |
| 155.133.245.37:27018   | 71           | 16.3MB         | 817.7KB       |
| 155.133.248.39:27017   | 71           | 14.1MB         | 685.5KB       |
| 162.254.193.74:27017   | 71           | 18.5MB         | 929.5KB       |
| 162.254.195.71:27017   | 71           | 19.5MB         | 855.5KB       |
| 205.196.6.215:27018    | 71           | 20MB           | 929KB         |
| 155.133.230.50:27018   | 70           | 15.5MB         | 795KB         |
| 155.133.239.51:27018   | 70           | 17.4MB         | 914.4KB       |
| 162.254.192.71:27017   | 70           | 18.9MB         | 732.8KB       |
| 162.254.196.68:27018   | 70           | 17.3MB         | 877.7KB       |
| 205.196.6.214:27017    | 70           | 20.3MB         | 906.6KB       |
| 155.133.226.75:27018   | 69           | 16.3MB         | 743.1KB       |
| 155.133.248.38:27018   | 69           | 14.8MB         | 718.6KB       |
| 155.133.253.50:27018   | 69           | 20.1MB         | 925.1KB       |
| 162.254.192.75:27017   | 69           | 16.4MB         | 740.6KB       |
| 162.254.192.75:27018   | 69           | 17.7MB         | 776.1KB       |
| 162.254.193.102:27017  | 69           | 18.6MB         | 878.4KB       |
| 146.66.155.38:27018    | 68           | 14.9MB         | 739.4KB       |
| 155.133.252.54:27018   | 68           | 15.5MB         | 659.6KB       |
| 162.254.196.67:27017   | 68           | 15MB           | 621.1KB       |
| 103.28.54.181:27018    | 67           | 19.7MB         | 836KB         |
| 155.133.230.34:27017   | 67           | 16.1MB         | 814.9KB       |
| 155.133.248.38:27017   | 67           | 14.4MB         | 739.5KB       |
| 155.133.226.78:27018   | 66           | 15.9MB         | 748.4KB       |
| 155.133.246.36:27017   | 66           | 16.9MB         | 856.7KB       |
| 103.28.54.165:27017    | 65           | 19.1MB         | 873.5KB       |
| 155.133.248.39:27018   | 65           | 13.6MB         | 616.5KB       |
| 162.254.197.54:27017   | 65           | 13.5MB         | 651.1KB       |
| 185.25.182.20:27018    | 65           | 16.7MB         | 701.5KB       |
| 103.28.54.165:27018    | 64           | 18MB           | 982KB         |
| 155.133.239.20:27017   | 64           | 15.3MB         | 781.1KB       |
| 155.133.253.34:27017   | 64           | 16.1MB         | 804.9KB       |
| 205.196.6.214:27018    | 64           | 18.7MB         | 836.1KB       |
| 155.133.230.34:27018   | 63           | 15.4MB         | 786.4KB       |
| 162.254.193.102:27018  | 63           | 16.9MB         | 816.4KB       |
| 162.254.195.71:27018   | 63           | 17.5MB         | 795.7KB       |
| 162.254.196.84:27017   | 63           | 15.3MB         | 790.7KB       |
| 162.254.197.39:27017   | 63           | 12.7MB         | 604.3KB       |
| 103.28.54.162:27018    | 62           | 17.8MB         | 849.9KB       |
| 103.28.54.181:27017    | 61           | 18.2MB         | 781.2KB       |
| 155.133.246.35:27017   | 61           | 13.2MB         | 636.6KB       |
| 162.254.192.74:27018   | 61           | 16.4MB         | 758.7KB       |
| 162.254.196.67:27018   | 59           | 12.1MB         | 577KB         |
| 162.254.199.163:27017  | 59           | 15.1MB         | 651.5KB       |
| 155.133.226.75:27017   | 58           | 14.6MB         | 768.8KB       |
| 155.133.239.51:27017   | 58           | 14.2MB         | 678.9KB       |
| 162.254.196.68:27017   | 58           | 12.6MB         | 585.5KB       |
| 103.28.54.178:27017    | 57           | 15.4MB         | 716.9KB       |
| 162.254.198.44:27017   | 57           | 12.6MB         | 621.4KB       |
| 162.254.193.74:27018   | 56           | 13.4MB         | 655.6KB       |
| 162.254.198.104:27018  | 56           | 13.7MB         | 711.1KB       |
| 162.254.192.71:27018   | 55           | 13.3MB         | 611.5KB       |
| 155.133.246.51:27018   | 54           | 13.6MB         | 711.1KB       |
| 162.254.192.87:27017   | 53           | 12.4MB         | 584KB         |
| 103.10.124.125:27018   | 52           | 15.8MB         | 621.8KB       |
| 155.133.253.34:27018   | 51           | 11.9MB         | 494.1KB       |
| 162.254.197.39:27018   | 51           | 12.6MB         | 658.6KB       |
| 155.133.246.52:27018   | 50           | 12.1MB         | 590.5KB       |
| 162.254.196.83:27018   | 49           | 11.3MB         | 471.5KB       |
| 103.10.124.122:27018   | 46           | 13.4MB         | 491.7KB       |
| 103.10.124.124:27018   | 46           | 14.2MB         | 538.3KB       |
| 103.10.124.123:27018   | 36           | 9.9MB          | 403.9KB       |
| 103.10.124.124:27017   | 36           | 10.3MB         | 446.1KB       |

**Comment by Step7750** [comment]
Yeah, it needs to do continual heartbeats to keep the GC connection alive.
