### ISSUE TITLE
CSGOFloat Market Checker extension always switching to first page of the skin

### ISSUE THREAD

**Issue by vQass** [csgofloat/inspect#173]
Hi, I'm using CSGOFloat Market Checker chrome extension. When I enter market url with specific page (start=x&count=y) it loads correct page and after ~2 second switches to the first page of the skin (sometimes it doesn't load correct page at all). 

For example:
https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Slate%20%28Field-Tested%29?start=100&count=100

Same thing when I refresh the page.
Is there any chance that you could fix that?

**Comment by wavpro** [comment]
I think you might wanna open an issue over at https://github.com/csgofloat/extension

**Comment by vQass** [comment]
Moved to extension issues, thanks

https://github.com/csgofloat/extension/issues/159#issue-1812225207
