### ISSUE TITLE
New version infinity load

### ISSUE THREAD

**Issue by denis-marecky** [csgofloat/inspect#174]
Donwloaded new version scrypt with proxy. Started via node

http://ip/  - invalid inspect structure, so it works 

http://ip/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561199066344867A29964192308D4758666955283261401 - just infinity loading, or 404

have old csgofloat instance runing on other server, same link works, but need new instance with proxies supproting

lust console.log:
debug: Got unhandled GC message 9173
debug: Sending GC message ClientHello
debug: Sending hello, setting timer for next attempt to 2000 ms
debug: Got handled GC message ClientWelcome
debug: Unknown SO type 2 with 1 items
debug: Unknown SO type 7 with 1 items
debug: GC connection established
info: SlimyCumbersomeTiger60 CSGO Client Ready!
debug: Got unhandled GC message 9173

can't find anything in any logs

**Comment by Step7750** [comment]
Your issue doesn't contain enough detail to help debug, closing.
