### ISSUE TITLE
[SOLUTION] Update version of node-steam-user to 4.29.0

### ISSUE THREAD

**Issue by lyeskin** [csgofloat/inspect#175]
Steam stopped to use `sentry` file for account management and now uses machine auth token for each account. The guys in `node-steam-user` repository already have fix for this issue, all you need is to update to 4.29.0 for this dependency. I already did this and created my own Docker image with the new version for `node-steam-user` and it works just fine.

Information: https://github.com/DoctorMcKay/node-steam-user/issues/447

**Comment by Step7750** [comment]
Feel free to send a PR.
