### ISSUE TITLE
Grade

### ISSUE THREAD

**Issue by un1uckycs** [csgofloat/inspect#177]
Your app is a real piece of shit that doesn't work properly. Always error 4 or 5

**Comment by un1uckycs** [comment]
AFTER 10 minutes this error
![image](https://github.com/csgofloat/inspect/assets/110466006/201ec8b7-27e5-4768-b38b-e53dc0b417ac)

**Comment by Step7750** [comment]
Your issue doesn't contain enough detail to help debug, closing.
