### ISSUE TITLE
Request not returning StatTrak amount and Name tag nickname

### ISSUE THREAD

**Issue by tfmart** [csgofloat/inspect#97]
I've noticed that lately the API has failed to return an item's name nickname from a name tag and the amount StatTrak kills. For example, I tried inspecting this AWP Redline, which has a name tag applied and has a bunch of kills on it's StatTrak:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/23082132/128548631-0b93262d-5af2-4ae9-b4a0-a26681ed0445.png">

Inspect link:
```
steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198066691636A16345977069D9244392637830798017
```

When I call the service, passing this inspect link in the `url` parameter, the response doesn't contain a `customname` value and the `killeatervalue` value is set to zero, which is not the expected response

**Comment by Step7750** [comment]
`customname` hasn't been returned by the GC for years.

`killeatervalue` isn't returned if it's a cached response. We haven't found it to be valuable to return this in the API with the storage overhead.
