### ISSUE TITLE
https://api.csgofloat.com/bulk? returns,  "error": "Bad Secret",     "code": 8,     "status": 400 with example Links

### ISSUE THREAD

**Issue by juanSLiberasoft** [csgofloat/inspect#99]
![image](https://user-images.githubusercontent.com/84023748/146024106-99d539c7-7b27-481f-b158-38c78375505c.png)

**Comment by Step7750** [comment]
As the message says, the public bulk endpoint is not allowed without a secret.

Please host your own instance to query this endpoint.
